config/routes.rb
Rails.application.routes.draw do
  root 'demo#index'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  has_and_belongs_to_many :pages
  has_many :section_edits
  has_many :sections, through: :section_edits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :subject, optional: true
  has_and_belongs_to_many :admin_users

  scope :visible, -> { where(visible: true) }
  scope :invisible, -> { where(visible: false) }
  scope :sorted, -> { order('position ASC') }
  scope :newest_first, -> { order('created_at DESC') }
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :section_edits
  has_many :admin_users, through: :section_edits

  scope :visible, -> { where(visible: true) }
  scope :invisible, -> { where(visible: false) }
  scope :sorted, -> { order('position ASC') }
  scope :newest_first, -> { order('created_at DESC') }
end

app/models/section_edit.rb
class SectionEdit < ApplicationRecord
  belongs_to :admin_user
  belongs_to :section
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :pages

  scope :visible, -> { where(visible: true) }
  scope :invisible, -> { where(visible: false) }
  scope :sorted, -> { order('position ASC') }
  scope :newest_first, -> { order('created_at DESC') }
  scope :search, ->(query) { where(['name LIKE ?', "%#{query}%"]) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout false

  def index
    render('index')
  end

  def hello
    @array = [1, 2, 3, 4, 5]
    render('hello')
  end

  def other_hello
    redirect_to(action: 'index')
  end

  def lynda
    redirect_to('http://lynda.com')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.sorted
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      flash[:notice] = 'Page created succesfully'
      redirect_to(pages_path)
    else
      render('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update(page_params)
      flash[:notice] = 'Page content updated succesfully'
      redirect_to(page_path(@page))
    else
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = "Page '#{@subject.name}' has been deleted succesfully."
    redirect_to(pages_path)
  end

  private

  def page_params
    params.require(:page).permit(:subject_id, :name, :position, :visible, :permalink)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def delete
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.sorted
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new({ name: 'default' })
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      flash[:notice] = 'Subject created Succesfully'
      redirect_to(subjects_path)
    else
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      flash[:notice] = 'Subject updated Succesfully'
      redirect_to(subject_path(@subject))
    else
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notcie] = "Subject '#{@subject.name}' destroyed successfully"
    redirect_to(subjects_path)
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :position, :visible)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/demo/hello.html.erb
<h1>This is from hello template</h1>
<% @array.each do |n|%>
    <%=  n %><br/>
<% end %>

app/views/demo/index.html.erb
<h1>Demo#index</h1>
<p>Hello World!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/delete.html.erb
<h1>Pages#delete</h1>
<p>Find me in app/views/pages/delete.html.erb</p>
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages delete">
  <h2>Delete Page</h2>
  <%= form_for(@page, :method => 'delete') do |f| %>
    <p>Are you sure you want to permanently delete this page?</p>
    <p class="reference-name"><%= f.object.name %></p>
    
    <div class="form-buttons">
      <%= f.submit("Delete Page") %>
    </div>
  <% end %>
</div>

app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb</p>

app/views/pages/index.html.erb
<% if !flash[:notice].blank? %>
    <div class="notice">
        <%= flash[:notice] %>
    </div>
<% end %>


<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<div class="pages index">
    <h2>Subjects</h2>

    <%= link_to("Add New Subject", new_page_path, :class => 'action new') %>

    <table class ="listing" summary = "Page list">
        <tr class="header">
            <th>#</th>
            <th>Subject ID</th>
            <th>Page</th>
            <th>Permalink</th>
            <th>Visible</th>
            <th>Sections</th>
            <th>Actions</th>
        </tr>

        <%= @pages.each do |page|%>
        <tr>
            <td><%= page.position %></td>
            <td><%= page.subject_id %></td>
            <td><%= page.name %></td>
            <td><%= page.permalink %></td>
            <td class="center"><%= page.visible ? 'Yes' : 'No' %></td>
            <td class="center"><%= page.page.sections.size %></td>
            <td class="actions">
                <%= link_to("Show", page_path(page), :class => 'action show') %>
                <%= link_to("Edit", edit_page_path(page), :class => 'action edit') %>
                <%= link_to("Delete", delete_page_path(page), :class => 'action delete') %>
            </td>
        </tr>
        <% end %>
    </table>
</div>

app/views/pages/new.html.erb
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>
<%= link_to("<< Back to List", pages_path, :class => 'back-link')  %>

<div class="pages new">
    <h2>Create page</h2>

    <%= form_for(@page) do |f| %>
        <table summary="Page form fields">
        <tr>
            <th>Name</th>
            <td><%= f.text_field(:name) %></td>
        </tr>
        <tr>
            <th>Subject ID</th>
            <td><%= f.text_field(:subject_id) %></td>
        </tr>
        <tr>
            <th>Permalink</th>
            <td><%= f.text_field(:permalink) %></td>
        </tr>
        <tr>
            <th>Position</th>
            <td><%= f.text_field(:position) %></td>
        </tr>
        <tr>
            <th>Visible</th>
            <td><%= f.text_field(:visible) %></td>
        </tr>
        </table>

        <div class="form-buttons">
            <%= f.submit("Create Page") %>
        </div>
        <% end %>
</div>

app/views/pages/show.html.erb
<% if !flash[:notice].blank? %>
    <div class="notice">
        <%= flash[:notice] %>
    </div>
<% end %>

<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>
<div>
    <table>
        <tr>
            <th>Name</th>
            <td><%= @subject.name %></td>
        </tr>
        <tr>
            <th>Position</th>
            <td><%= @subject.position %></td>
        </tr>
        <tr>
            <th>Visible?</th>
            <td><%= @subject.visible ? 'true' : 'false' %></td>
        </tr>
        <tr>
            <th>Created</th>
            <td><%= @subject.created_at %></td>
        </tr>
        <tr>
            <th>Updated at</th>
            <td><%= @subject.updated_at %></td>
        </tr>
    </table>
</div>

app/views/sections/delete.html.erb
<h1>Sections#delete</h1>
<p>Find me in app/views/sections/delete.html.erb</p>

app/views/sections/edit.html.erb
<h1>Sections#edit</h1>
<p>Find me in app/views/sections/edit.html.erb</p>

app/views/sections/index.html.erb
<h1>Sections#index</h1>
<p>Find me in app/views/sections/index.html.erb</p>

app/views/sections/new.html.erb
<h1>Sections#new</h1>
<p>Find me in app/views/sections/new.html.erb</p>

app/views/sections/show.html.erb
<h1>Sections#show</h1>
<p>Find me in app/views/sections/show.html.erb</p>

app/views/subjects/delete.html.erb
<h1>Subjects#delete</h1>
<p>Find me in app/views/subjects/delete.html.erb</p>
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Subject</h2>
  <%= form_for(@subject, :method => 'delete') do |f| %>
    <p>Are you sure you want to permanently delete this subject?</p>
    <p class="reference-name"><%= f.object.name %></p>
    
    <div class="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>
  <% end %>
</div>

app/views/subjects/edit.html.erb
<h1>Subjects#edit</h1>
<p>Find me in app/views/subjects/edit.html.erb</p>

<%= link_to("<< Back to List", subjects_path, :class => 'back-link')  %>

<div class="subjects edit">
    <h2>Edit Subject</h2>

    <%= form_for(@subject) do |f| %>
        <table summary="Subject form fields">
        <tr>
            <th>Name</th>
            <td><%= f.text_field(:name) %></td>
        </tr>
        <tr>
            <th>Position</th>
            <td><%= f.text_field(:position) %></td>
        </tr>
        <tr>
            <th>Visible</th>
            <td><%= f.text_field(:visible) %></td>
        </tr>
        </table>

        <div class="form-buttons">
            <%= f.submit("Update Subject") %>
        </div>
        <% end %>
</div>

app/views/subjects/index.html.erb
<% if !flash[:notice].blank? %>
    <div class="notice">
        <%= flash[:notice] %>
    </div>
<% end %>


<h1>Subjects#index</h1>
<p>Find me in app/views/subjects/index.html.erb</p>
<div class="subjects index">
    <h2>Subjects</h2>

    <%= link_to("Add New Subject", new_subject_path, :class => 'action new') %>

    <table class ="listing" summary = "Subject list">
        <tr class="header">
            <th>#</th>
            <th>Subject</th>
            <th>Visible</th>
            <th>Pages</th>
            <th>Actions</th>
        </tr>

        <%= @subjects.each do |subject|%>
        <tr>
            <td><%= subject.position %></td>
            <td><%= subject.name %></td>
            <td class="center"><%= subject.visible ? 'Yes' : 'No' %></td>
            <td class="center"><%= subject.pages.size %></td>
            <td class="actions">
                <%= link_to("Show", subject_path(subject), :class => 'action show') %>
                <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
                <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
            </td>
        </tr>
        <% end %>
    </table>
</div>

app/views/subjects/new.html.erb
<h1>Subjects#new</h1>
<p>Find me in app/views/subjects/new.html.erb</p>
<%= link_to("<< Back to List", subjects_path, :class => 'back-link')  %>

<div class="subjects new">
    <h2>Create Subject</h2>

    <%= form_for(@subject) do |f| %>
        <table summary="Subject form fields">
        <tr>
            <th>Name</th>
            <td><%= f.text_field(:name) %></td>
        </tr>
        <tr>
            <th>Position</th>
            <td><%= f.text_field(:position) %></td>
        </tr>
        <tr>
            <th>Visible</th>
            <td><%= f.text_field(:visible) %></td>
        </tr>
        </table>

        <div class="form-buttons">
            <%= f.submit("Create Subject") %>
        </div>
        <% end %>
</div>

app/views/subjects/show.html.erb
<% if !flash[:notice].blank? %>
    <div class="notice">
        <%= flash[:notice] %>
    </div>
<% end %>

<h1>Subjects#show</h1>
<p>Find me in app/views/subjects/show.html.erb</p>
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>
<div>
    <table>
        <tr>
            <th>Name</th>
            <td><%= @subject.name %></td>
        </tr>
        <tr>
            <th>Position</th>
            <td><%= @subject.position %></td>
        </tr>
        <tr>
            <th>Visible?</th>
            <td><%= @subject.visible ? 'true' : 'false' %></td>
        </tr>
        <tr>
            <th>Created</th>
            <td><%= @subject.created_at %></td>
        </tr>
        <tr>
            <th>Updated at</th>
            <td><%= @subject.updated_at %></td>
        </tr>
    </table>
</div>